version: "3"

x-logging:
  &default-logging
  options:
    max-file: '1'
    compress: 'false'
  driver: local

networks:
  autonity_network:
    name: autonity_network
    external: false
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_SUBNET_MASK}/24

services:
  whoami:
    image: containous/whoami
    container_name: whoami
    networks:
      autonity_network:
        ipv4_address: ${DOCKER_SUBNET_PREFIX}.7
